const SteamItemFilters = require('../../models/SteamItemFilters');

module.exports = async () => {
  let filters = await SteamItemFilters.findOne();

  if (!filters) {
    filters = new SteamItemFilters({
      '440': {
        Class: ['demoman', 'engineer', 'heavy', 'medic', 'pyro', 'scout', 'sniper', 'soldier', 'spy'],
        Quality: ['genuine', 'haunted', 'strange', 'unique', 'unusual'],
        Type: [
          'action',
          'building',
          'cosmetic',
          'craft item',
          'crate',
          'gift',
          'melee weapon',
          'party favor',
          'primary weapon',
          'secondary pda',
          'secondary weapon',
          'spellbook page',
          'supply crate',
          'taunt 1',
          'usable item',
        ],
        Weapon: [],
      },
      '570': {
        Rarity: ['arcana', 'common', 'immortal', 'legendary', 'mythical', 'rare', 'seasonal', 'uncommon'],
        Quality: [
          'ascendant',
          'auspicious',
          'autographed',
          'base',
          'corrupted',
          'cursed',
          'elder',
          'exalted',
          'frozen',
          'genuine',
          'heroic',
          'infused',
          'inscribed',
          'standard',
          'unusual',
        ],
        Hero: [
          'abaddon',
          'alchemist',
          'ancient apparition',
          'anti-mage',
          'arc warden',
          'axe',
          'bane',
          'batrider',
          'beastmaster',
          'bloodseeker',
          'bounty hunter',
          'brewmaster',
          'bristleback',
          'broodmother',
          'centaur warrunner',
          'chaos knight',
          'chen',
          'clinkz',
          'clockwerk',
          'crystal maiden',
          'dark seer',
          'dark willow',
          'dazzle',
          'death prophet',
          'disruptor',
          'doom',
          'dragon knight',
          'drow ranger',
          'earth spirit',
          'earthshaker',
          'elder titan',
          'ember spirit',
          'enchantress',
          'enigma',
          'faceless void',
          'grimstroke',
          'gyrocopter',
          'huskar',
          'invoker',
          'invoker (kid)',
          'io',
          'jakiro',
          'juggernaut',
          'keeper of the light',
          'kunkka',
          'legion commander',
          'leshrac',
          'lich',
          'lifestealer',
          'lina',
          'lion',
          'lone druid',
          'luna',
          'lycan',
          'magnus',
          'mars',
          'medusa',
          'meepo',
          'mirana',
          'monkey king',
          'morphling',
          'naga siren',
          "nature's prophet",
          'necrophos',
          'night stalker',
          'nyx assassin',
          'ogre magi',
          'omniknight',
          'oracle',
          'other',
          'outworld devourer',
          'pangolier',
          'phantom assassin',
          'phantom lancer',
          'phoenix',
          'puck',
          'pudge',
          'pugna',
          'queen of pain',
          'razor',
          'riki',
          'rubick',
          'sand king',
          'shadow demon',
          'shadow fiend',
          'shadow shaman',
          'silencer',
          'skywrath mage',
          'slardar',
          'slark',
          'snapfire',
          'sniper',
          'spectre',
          'spirit breaker',
          'storm spirit',
          'sven',
          'techies',
          'templar assassin',
          'terrorblade',
          'tidehunter',
          'timbersaw',
          'tinker',
          'tiny',
          'treant protector',
          'troll warlord',
          'tusk',
          'underlord',
          'undying',
          'ursa',
          'vengeful spirit',
          'venomancer',
          'viper',
          'visage',
          'void spirit',
          'warlock',
          'weaver',
          'windranger',
          'winter wyvern',
          'witch doctor',
          'wraith king',
          'zeus',
        ],
        Type: [
          'announcer',
          'bundle',
          'courier',
          'cursor pack',
          'dire creeps',
          'dire towers',
          'emoticon tool',
          'gem / rune',
          'hud skin',
          'kill streak effect',
          'league',
          'loading screen',
          'misc',
          'music',
          'pennant',
          'player card',
          'radiant creeps',
          'radiant towers',
          'recipe',
          'retired chest',
          'taunt',
          'terrain',
          'tool',
          'treasure',
          'treasure key',
          'versus screen',
          'ward',
          'wearable',
        ],
        Slot: [
          'ability 1',
          'ability 2',
          'ability 3',
          'ability 4',
          'announcer',
          'armor',
          'arms',
          'back',
          'belt',
          'body - head',
          'courier',
          'cursor pack',
          'dire creeps',
          'dire towers',
          'gloves',
          'head',
          'heroic effigy',
          'hud skin',
          'kill streak effects',
          'legs',
          'loading screen',
          'mega-kill announcer',
          'misc',
          'mount',
          'multikill banner',
          'music',
          'n/a',
          'neck',
          'off-hand',
          'persona',
          'radiant creeps',
          'radiant towers',
          'shapeshift',
          'shoulder',
          'summoned unit',
          'tail',
          'taunt',
          'terrain',
          'ultimate',
          'versus screen',
          'voice',
          'ward',
          'weapon',
          'weather',
        ],
      },
      '730': {
        Rarity: [
          'base grade',
          'classified',
          'consumer grade',
          'contraband',
          'covert',
          'distinguished',
          'exceptional',
          'exotic',
          'extraordinary',
          'high grade',
          'industrial grade',
          'master',
          'mil-spec grade',
          'remarkable',
          'restricted',
          'stock',
          'superior',
        ],
        Quality: ['genuine', 'normal', 'souvenir', 'stattrak™', '★'],
        Type: [
          'agent',
          'c4',
          'collectible',
          'container',
          'gift',
          'gloves',
          'graffiti',
          'key',
          'knife',
          'machinegun',
          'music kit',
          'pass',
          'patch',
          'pistol',
          'rifle',
          'shotgun',
          'smg',
          'sniper rifle',
          'sticker',
          'tag',
          'tool',
        ],
        Weapon: [
          'ak-47',
          'aug',
          'awp',
          'bayonet',
          'bowie knife',
          'butterfly knife',
          'c4 explosive',
          'classic knife',
          'cz75-auto',
          'desert eagle',
          'dual berettas',
          'falchion knife',
          'famas',
          'five-seven',
          'flip knife',
          'g3sg1',
          'galil ar',
          'glock-18',
          'gut knife',
          'huntsman knife',
          'karambit',
          'm249',
          'm4a1-s',
          'm4a4',
          'm9 bayonet',
          'mac-10',
          'mag-7',
          'mp5-sd',
          'mp7',
          'mp9',
          'navaja knife',
          'negev',
          'nomad knife',
          'nova',
          'p2000',
          'p250',
          'p90',
          'paracord knife',
          'pp-bizon',
          'r8 revolver',
          'sawed-off',
          'scar-20',
          'sg 553',
          'shadow daggers',
          'skeleton knife',
          'ssg 08',
          'stiletto knife',
          'survival knife',
          'talon knife',
          'tec-9',
          'ump-45',
          'ursus knife',
          'usp-s',
          'xm1014',
        ],
        ItemSet: [
          'shattered web agents',
          'the 2018 inferno collection',
          'the 2018 nuke collection',
          'the alpha collection',
          'the arms deal 2 collection',
          'the arms deal 3 collection',
          'the arms deal collection',
          'the assault collection',
          'the aztec collection',
          'the baggage collection',
          'the bank collection',
          'the blacksite collection',
          'the bravo collection',
          'the breakout collection',
          'the cache collection',
          'the canals collection',
          'the chop shop collection',
          'the chroma 2 collection',
          'the chroma 3 collection',
          'the chroma collection',
          'the clutch collection',
          'the cobblestone collection',
          'the cs20 collection',
          'the danger zone collection',
          'the dust 2 collection',
          'the dust collection',
          'the esports 2013 collection',
          'the esports 2013 winter collection',
          'the esports 2014 summer collection',
          'the falchion collection',
          'the gamma 2 collection',
          'the gamma collection',
          'the glove collection',
          'the gods and monsters collection',
          'the horizon collection',
          'the huntsman collection',
          'the inferno collection',
          'the italy collection',
          'the lake collection',
          'the militia collection',
          'the mirage collection',
          'the norse collection',
          'the nuke collection',
          'the office collection',
          'the operation hydra collection',
          'the overpass collection',
          'the phoenix collection',
          'the prisma 2 collection',
          'the prisma collection',
          'the revolver case collection',
          'the rising sun collection',
          'the safehouse collection',
          'the shadow collection',
          'the shattered web collection',
          'the spectrum 2 collection',
          'the spectrum collection',
          'the st. marc collection',
          'the train collection',
          'the vanguard collection',
          'the vertigo collection',
          'the wildfire collection',
          'the winter offensive collection',
          'the x-ray collection',
        ],
        Exterior: ['battle-scarred', 'factory new', 'field-tested', 'minimal wear', 'not painted', 'well-worn'],
      },
      '753': {
        droprate: [],
        Game: [],
        CardBorder: [],
        item_class: [],
      },
      '252490': {
        itemclass: [],
        steamcat: [],
      },
    });

    await filters.save();
  }
};
